name: 'Release Monitor Slack'
description: 'Will send updates to slack based on github wiki pages being updated'
author: 'kpfaulkner'
on: release
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'

